### ISSUE TITLE
Cert gen fails

### ISSUE THREAD

**Issue by sCHween** [plesk/letsencrypt-plesk#101]
Hi there

for a domain the cert gen fails with the following log entry:

```
2016-05-20 12:27:20,871:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): 127.0.0.1
2016-05-20 12:27:20,986:DEBUG:requests.packages.urllib3.connectionpool:"POST /enterprise/control/agent.php HTTP/1.1" 200 None
2016-05-20 12:27:20,989:DEBUG:letsencrypt_plesk.api_client:Plesk API-RPC response: <?xml version="1.0" encoding="UTF-8"?>
<packet version="1.6.7.0">
  <site>
    <get>
      <result>
        <status>error</status>
        <errcode>1023</errcode>
        <errtext>Unkown filter value : wie-gseehs​ch-us.ch</errtext>
      </result>
    </get>
  </site>
</packet>

2016-05-20 12:27:20,992:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/psa/var/modules/letsencrypt/venv.Cr2rM/lib/python2.7/site-packages/certbot/auth_handler.py", line 108, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/usr/local/psa/var/modules/letsencrypt/venv.Cr2rM/lib/python2.7/site-packages/letsencrypt_plesk/configurator.py", line 75, in perform
    responses.append(self.plesk_challenges[domain].perform(x))
  File "/usr/local/psa/var/modules/letsencrypt/venv.Cr2rM/lib/python2.7/site-packages/letsencrypt_plesk/challenge.py", line 28, in perform
    self._init_domain_props()
  File "/usr/local/psa/var/modules/letsencrypt/venv.Cr2rM/lib/python2.7/site-packages/letsencrypt_plesk/challenge.py", line 54, in _init_domain_props
    error_text = str(api_result['errtext'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u200b' in position 32: ordinal not in range(128)
```

any idea on that?
Thanks for the fish

**Comment by xgin** [comment]
In version 2.0 we replaced Python-based certbot with PHP-based client: unicode issues should be fixed now.
