### ISSUE TITLE
install certificate end error OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by panaceya** [plesk/letsencrypt-plesk#131]
```

Failed letsencrypt execution: Saving debug log to /usr/local/psa/var/modules/letsencrypt/logs/letsencrypt.log
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Renewal conf file /usr/local/psa/var/modules/letsencrypt/etc/renewal/domain.com-0001.conf is broken. Skipping.
Renewal conf file /usr/local/psa/var/modules/letsencrypt/etc/renewal/domain.com.conf is broken. Skipping.
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for domain.com
http-01 challenge for www.domain.com
Starting new HTTPS connection (1): 127.0.0.1
Waiting for verification...
Cleaning up challenges
Generating key (2048 bits): /usr/local/psa/var/modules/letsencrypt/etc/keys/0002_key-certbot.pem
Creating CSR: /usr/local/psa/var/modules/letsencrypt/etc/csr/0002_csr-certbot.pem
Non-standard path(s), might not work with crontab installed by your operating system package manager
An unexpected error occurred:
OSError: [Errno 2] No such file or directory
Please see the logfiles in /usr/local/psa/var/modules/letsencrypt/logs for more details. 
```

File /usr/local/psa/var/modules/letsencrypt/log/letsencrypt.log contain this:
```
2016-11-04 20:43:08,624:INFO:certbot.crypto_util:Generating key (2048 bits): /usr/local/psa/var/modules/letsencrypt/etc/keys/0002_key-certbot.pem
2016-11-04 20:43:08,628:INFO:certbot.crypto_util:Creating CSR: /usr/local/psa/var/modules/letsencrypt/etc/csr/0002_csr-certbot.pem
2016-11-04 20:43:08,628:DEBUG:certbot.client:CSR: CSR(file='/usr/local/psa/var/modules/letsencrypt/etc/csr/0002_csr-certbot.pem', data='x', form='der'), domains: [u'domain.com', u'www.domain.com']
2016-11-04 20:43:08,628:DEBUG:acme.client:Requesting issuance...
2016-11-04 20:43:08,628:DEBUG:acme.client:Serialized JSON: {"resource": "new-cert", "csr": "x"}
2016-11-04 20:43:08,630:DEBUG:acme.jose.json_util:Omitted empty fields: typ=None, x5c=(), crit=(), x5tS256=None, kid=None, cty=None, jwk=None, x5u=None, x5t=None, alg=None, jku=None
2016-11-04 20:43:08,632:DEBUG:acme.jose.json_util:Omitted empty fields: typ=None, x5c=(), crit=(), x5tS256=None, kid=None, cty=None, x5u=None, x5t=None, jku=None, nonce=None
2016-11-04 20:43:08,633:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-cert. args: (), kwargs: {'headers': {'Accept': 'application/pkix-cert'}, 'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "x"}}, "protected": "x", "payload": "x", "signature": "x"}'}
2016-11-04 20:43:08,944:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-cert HTTP/1.1" 201 1292
2016-11-04 20:43:08,944:DEBUG:root:Received <Response [201]>. Headers: {'Content-Length': '1292', 'Expires': 'Fri, 04 Nov 2016 20:43:08 GMT', 'Boulder-Request-Id': '-', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/issuer-cert>;rel="up"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/cert/x', 'Pragma': 'no-cache', 'Boulder-Requester': '5852913', 'Date': 'Fri, 04 Nov 2016 20:43:08 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/pkix-cert', 'Replay-Nonce': ''}. Content: 'x'
2016-11-04 20:43:08,945:DEBUG:acme.client:Received response <Response [201]> (headers: {'Content-Length': '1292', 'Expires': 'Fri, 04 Nov 2016 20:43:08 GMT', 'Boulder-Request-Id': '-', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/issuer-cert>;rel="up"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/cert/x', 'Pragma': 'no-cache', 'Boulder-Requester': '5852913', 'Date': 'Fri, 04 Nov 2016 20:43:08 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/pkix-cert', 'Replay-Nonce': 'x'}): 'x'
2016-11-04 20:43:08,984:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/acme/issuer-cert. args: (), kwargs: {'headers': {'Accept': 'application/pkix-cert'}}
2016-11-04 20:43:09,238:DEBUG:requests.packages.urllib3.connectionpool:"GET /acme/issuer-cert HTTP/1.1" 200 1174
2016-11-04 20:43:09,239:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '1174', 'Expires': 'Fri, 04 Nov 2016 20:43:09 GMT', 'Boulder-Request-Id': 'x', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Fri, 04 Nov 2016 20:43:09 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/pkix-cert', 'Replay-Nonce': 'x'}. Content: 'x'
2016-11-04 20:43:09,239:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '1174', 'Expires': 'Fri, 04 Nov 2016 20:43:09 GMT', 'Boulder-Request-Id': 'qu4mOMw5jekmznn83hL8ZPOkUNvleea7sOlbbv6cHFY', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Fri, 04 Nov 2016 20:43:09 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/pkix-cert', 'Replay-Nonce': ''}): 'x'
2016-11-04 20:43:09,261:WARNING:certbot.client:Non-standard path(s), might not work with crontab installed by your operating system package manager
2016-11-04 20:43:09,262:DEBUG:certbot.storage:Archive directory /usr/local/psa/var/modules/letsencrypt/etc/archive/domain.com-0002 and live directory /usr/local/psa/var/modules/letsencrypt/etc/live/domain.com-0002 created.
2016-11-04 20:43:09,263:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/psa/var/modules/letsencrypt/venv/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/psa/var/modules/letsencrypt/venv.JkYWK/lib/python2.7/site-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/usr/local/psa/var/modules/letsencrypt/venv.JkYWK/lib/python2.7/site-packages/certbot/main.py", line 511, in run
    action, lineage = _auth_from_domains(le_client, config, domains)
  File "/usr/local/psa/var/modules/letsencrypt/venv.JkYWK/lib/python2.7/site-packages/certbot/main.py", line 100, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/usr/local/psa/var/modules/letsencrypt/venv.JkYWK/lib/python2.7/site-packages/certbot/client.py", line 298, in obtain_and_enroll_certificate
    configuration.RenewerConfiguration(self.config.namespace))
  File "/usr/local/psa/var/modules/letsencrypt/venv.JkYWK/lib/python2.7/site-packages/certbot/storage.py", line 796, in new_lineage
    target[kind])
OSError: [Errno 2] No such file or directory
```
Real domain replaced with domain.com

Plugin version 1.9, Plesk version 12.5.30 with update #51. OS CloudLinux 7.

**Comment by xgin** [comment]
The configuration of your CloudLinux (probably CageFS extension) does not allow to create a symlink to non-existing file (but it is valid filesystem operation):
http://docs.cloudlinux.com/index.html?symlink_owner_match_protection.html
The issue with letsencrypt did not come alone, other operations in Plesk might have been broken. At least I have found this KB: https://kb.plesk.com/en/130034
Propose to either disable this protection with `fs.enforce_symlinksifowner = 0` or allow `psaadm` user with `fs.symlinkown_gid`

**Comment by panaceya** [comment]
Sanks, but have same error with `fs.enforce_symlinksifowner = 0` and `fs.symlinkown_gid = 1000` in sysctl.

**Comment by xgin** [comment]
@panaceya try to disable {{fs.protected_symlinks_create}}

**Comment by strausmann** [comment]
@panaceya give it another way to resolve this issue? This is a little bit to more, disable the fs.protected_symlinks_create function. Thanks

**Comment by olegburca** [comment]
@xgin, thanks, it worked for me.
