### ISSUE TITLE
ContextualVersionConflict: (cryptography 1.3.1 (/opt/psa/var/modules/letsencrypt/venv.RFhL6/lib/python2.7/site-packages), Requirement.parse('cryptography>=1.3.4; extra == "security"'), set(['requests']))

### ISSUE THREAD

**Issue by alessiodionisi** [plesk/letsencrypt-plesk#141]
Traceback (most recent call last):
  File "/opt/psa/var/modules/letsencrypt/venv/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/psa/var/modules/letsencrypt/venv.RFhL6/lib/python2.7/site-packages/certbot/main.py", line 825, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/local/psa/var/modules/letsencrypt/venv.RFhL6/lib/python2.7/site-packages/certbot/plugins/disco.py", line 183, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/local/psa/var/modules/letsencrypt/venv.RFhL6/lib/python2.7/site-packages/certbot/plugins/disco.py", line 34, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/local/psa/var/modules/letsencrypt/venv.RFhL6/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2290, in load
    self.require(*args, **kwargs)
  File "/usr/local/psa/var/modules/letsencrypt/venv.RFhL6/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2307, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/psa/var/modules/letsencrypt/venv.RFhL6/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (cryptography 1.3.1 (/opt/psa/var/modules/letsencrypt/venv.RFhL6/lib/python2.7/site-packages), **Requirement.parse('cryptography>=1.3.4; extra == "security"'), set(['requests']))**

**Comment by xgin** [comment]
Thank you for reporting.
We will fix it ASAP.

**Comment by alessiodionisi** [comment]
I've tried to update cryptography package with pip without success

**Comment by xgin** [comment]
@alessiodionisi the dependency has been fixed - try to reinstall the extension.

**Comment by alessiodionisi** [comment]
It works perfectly 😄 

Thank you
