### ISSUE TITLE
Connection aborted, error 10054

### ISSUE THREAD

**Issue by Riedi2070** [plesk/letsencrypt-plesk#154]
I installed last Update Onyx 17.0.17 Update Nr. 14. I reinstall the let's encrpyt extension. But no changes, I get error:

Fehler: Fehler bei der Installation des SSL-Zertifikats von Let's Encrypt: Failed letsencrypt execution: Saving debug log to C:\Program Files (x86)\Parallels\Plesk\var\modules\letsencrypt\logs\letsencrypt.log Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org Obtaining a new certificate Performing the following challenges: http-01 challenge for www.xxxxxxx.com Starting new HTTPS connection (1): 127.0.0.1 Cleaning up challenges An unexpected error occurred: ConnectionError: ('Connection aborted.', error(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen')) Please see the logfiles in C:\Program Files (x86)\Parallels\Plesk\var\modules\letsencrypt\logs for more details.

Windows Server 2012 R2 with IIS 8.5 and Plesk Onyx 17.0.17 Update Nr. 14

I think its a problem with dns binding, but I don't know, how I can fix it. Have somebody any idea?

**Comment by TGRHavoc** [comment]
Getting the same issue. 

This is from the `letsencrypt.log` file, it may help:

```Traceback (most recent call last):
  File "C:\Program Files (x86)\Plesk\python\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Program Files (x86)\Plesk\python\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Program Files (x86)\Plesk\var\modules\letsencrypt\venv\Scripts\certbot.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\program files (x86)\plesk\var\modules\letsencrypt\venc98f.tmp\lib\site-packages\certbot\main.py", line 882, in main
    return config.func(config, plugins)
  File "c:\program files (x86)\plesk\var\modules\letsencrypt\venc98f.tmp\lib\site-packages\certbot\main.py", line 608, in run
    action, lineage = _auth_from_available(le_client, config, domains, certname)
  File "c:\program files (x86)\plesk\var\modules\letsencrypt\venc98f.tmp\lib\site-packages\certbot\main.py", line 108, in _auth_from_available
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "c:\program files (x86)\plesk\var\modules\letsencrypt\venc98f.tmp\lib\site-packages\certbot\client.py", line 294, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "c:\program files (x86)\plesk\var\modules\letsencrypt\venc98f.tmp\lib\site-packages\certbot\client.py", line 265, in obtain_certificate
    self.config.allow_subset_of_names)
  File "c:\program files (x86)\plesk\var\modules\letsencrypt\venc98f.tmp\lib\site-packages\certbot\auth_handler.py", line 73, in get_authorizations
    resp = self._solve_challenges()
  File "c:\program files (x86)\plesk\var\modules\letsencrypt\venc98f.tmp\lib\site-packages\certbot\auth_handler.py", line 111, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "c:\program files (x86)\plesk\var\modules\letsencrypt\venc98f.tmp\lib\site-packages\letsencrypt_plesk\configurator.py", line 77, in perform
    responses.append(self.plesk_challenges[domain].perform(x))
  File "c:\program files (x86)\plesk\var\modules\letsencrypt\venc98f.tmp\lib\site-packages\letsencrypt_plesk\challenge.py", line 28, in perform
    self._init_domain_props()
  File "c:\program files (x86)\plesk\var\modules\letsencrypt\venc98f.tmp\lib\site-packages\letsencrypt_plesk\challenge.py", line 50, in _init_domain_props
    response = self.plesk_api_client.request(request)
  File "c:\program files (x86)\plesk\var\modules\letsencrypt\venc98f.tmp\lib\site-packages\letsencrypt_plesk\api_client.py", line 94, in request
    response = requests.post(self.get_api_uri(), data=request, headers=headers, verify=False)
  File "c:\program files (x86)\plesk\var\modules\letsencrypt\venc98f.tmp\lib\site-packages\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "c:\program files (x86)\plesk\var\modules\letsencrypt\venc98f.tmp\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\program files (x86)\plesk\var\modules\letsencrypt\venc98f.tmp\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\program files (x86)\plesk\var\modules\letsencrypt\venc98f.tmp\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\program files (x86)\plesk\var\modules\letsencrypt\venc98f.tmp\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))```

**Comment by xgin** [comment]
Since version 2.0 API requests are performed internally.
The issue should be fixed now.
