### ISSUE TITLE
ExpatError in case Plesk port 8443 is customized

### ISSUE THREAD

**Issue by Heidschnucke** [plesk/letsencrypt-plesk#30]
Hi!

I have a problem executing letsencrypt-plesk:
```
Fehler: Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: 2015-12-11 01:45:31,809:WARNING:letsencrypt.cli:Root (sudo) is required to run most of letsencrypt functionality.
An unexpected error occurred:
ExpatError: mismatched tag: line 1, column 1027
Please see the logfiles in /opt/psa/var/modules/letsencrypt/logs for more details.
```
My first guess was, that this error is similar to https://github.com/plesk/letsencrypt-plesk/issues/13 but this seems to be another error. 

Here the contents of /opt/psa/var/modules/letsencrypt/logs/:
```
2015-12-11 00:45:35,778:INFO:letsencrypt.auth_handler:Performing the following challenges:
2015-12-11 00:45:35,778:INFO:letsencrypt.auth_handler:http-01 challenge for XXX.de
2015-12-11 00:45:35,778:INFO:letsencrypt.auth_handler:http-01 challenge for www.XXX.de
2015-12-11 00:45:35,786:DEBUG:letsencrypt_plesk.api_client:Plesk API-RPC request: <?xml version="1.0" ?><packet><site><get><filter><name>XXX.de</name></filter><dataset><hosting/></dataset></get></site></packet>
2015-12-11 00:45:35,788:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): 127.0.0.1
2015-12-11 00:45:35,952:DEBUG:requests.packages.urllib3.connectionpool:"POST /enterprise/control/agent.php HTTP/1.1" 404 1039
2015-12-11 00:45:35,953:DEBUG:letsencrypt_plesk.api_client:Plesk API-RPC response: <html><head><title>Apache Tomcat/7.0.26 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - /enterprise/control/agent.php</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/enterprise/control/agent.php</u></p><p><b>description</b> <u>The requested resource (/enterprise/control/agent.php) is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.26</h3></body></html>
2015-12-11 00:45:35,956:DEBUG:letsencrypt.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 115, in _solve_challenges
    dv_resp = self.dv_auth.perform(self.dv_c)
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt_plesk/configurator.py", line 73, in perform
    responses.append(self.plesk_challenges[domain].perform(x))
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt_plesk/challenge.py", line 31, in perform
    content=validation.encode())
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt_plesk/challenge.py", line 40, in _put_validation_file
    response = self.plesk_api_client.request(request)
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt_plesk/api_client.py", line 60, in request
    return XmlToDict(response.text.encode('utf-8'))
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt_plesk/api_client.py", line 150, in __init__
    dom = parseString(data)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1930, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: mismatched tag: line 1, column 1027

2015-12-11 00:45:35,957:DEBUG:letsencrypt.error_handler:Calling registered functions
2015-12-11 00:45:35,957:INFO:letsencrypt.auth_handler:Cleaning up challenges
2015-12-11 00:45:35,958:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/psa/var/modules/letsencrypt//venv/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1283, in main
    return args.func(args, config, plugins)
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 470, in run
    lineage = _auth_from_domains(le_client, config, domains)
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 336, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt/client.py", line 283, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt/client.py", line 266, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt/client.py", line 224, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 80, in get_authorizations
    cont_resp, dv_resp = self._solve_challenges()
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 115, in _solve_challenges
    dv_resp = self.dv_auth.perform(self.dv_c)
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt_plesk/configurator.py", line 73, in perform
    responses.append(self.plesk_challenges[domain].perform(x))
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt_plesk/challenge.py", line 31, in perform
    content=validation.encode())
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt_plesk/challenge.py", line 40, in _put_validation_file
    response = self.plesk_api_client.request(request)
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt_plesk/api_client.py", line 60, in request
    return XmlToDict(response.text.encode('utf-8'))
  File "/usr/local/psa/var/modules/letsencrypt/venv.jJNaH/local/lib/python2.7/site-packages/letsencrypt_plesk/api_client.py", line 150, in __init__
    dom = parseString(data)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1930, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: mismatched tag: line 1, column 1027
```

**Comment by MatrixCrawler** [comment]
It seems that your plesk installation is missing the *enterprise/control/agent.php* file.
this is needed to read and modify your dns records.

i would assume that this is not an issue with the plugin but with your plesk installation

**Comment by Heidschnucke** [comment]
Thank you for your answer.

The agent.php is reachable, but maybe there is a problem with my plesk installation since I switched the plesk port 8443 to 8881.
The agent.php can be reached by 
https://XYZ.de:8881/enterprise/control/agent.php

On another server from this provider with the default port there are no problems. The plesk letsencrypt plugin works out of the box.

**Comment by MatrixCrawler** [comment]
It seems that the port is hardcoded to 8443 currently.

The init call in the configurator.py does not pass a port for the PleskApiClient (as far as i understand the py code)
The constructor of the PleskApiClient sets the port to 8443 if no other port is specified

**Comment by sajeena123** [comment]
http://pastebin.com/LSnJCawG

I am getting error while trying to install the letsencrypt, Let me know whats the error
