### ISSUE TITLE
Problems with Generating for Server Cert

### ISSUE THREAD

**Issue by Huskynarr** [plesk/letsencrypt-plesk#53]
I didn't find the Error. 
I want to create a new certificate for the site, its the same name like the hostname.
But i want it to use as Server Certifiacate, for Plesk and Something, but i get always this Messge in Plesk.

**Plesk:**
```Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: 2015-12-31 14:48:28,832:WARNING:letsencrypt.cli:Root (sudo) is required to run most of letsencrypt functionality.
An unexpected error occurred:
KeyError: 'vrt_hst'
Please see the logfiles in /opt/psa/var/modules/letsencrypt/logs for more details.```

The Logs are longer, but the rest of the Log is uninteresting. Only funny that tail say he didn't find the log, but can write in a existing log.

**Logs:**
```plain
2015-12-31 14:48:30,498:DEBUG:letsencrypt.error_handler:Encountered exception: Traceback (most recent call last):                                                                                         
  File "/usr/local/psa/var/modules/letsencrypt/venv.qKGL3/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 115, in _solve_challenges dv_resp = self.dv_auth.perform(self.dv_c) 
File "/usr/local/psa/var/modules/letsencrypt/venv.qKGL3/local/lib/python2.7/site-packages/letsencrypt_plesk/configurator.py", line 75, in perform
    responses.append(self.plesk_challenges[domain].perform(x))
  File "/usr/local/psa/var/modules/letsencrypt/venv.qKGL3/local/lib/python2.7/site-packages/letsencrypt_plesk/challenge.py", line 31, in perform
    content=validation.encode())
  File "/usr/local/psa/var/modules/letsencrypt/venv.qKGL3/local/lib/python2.7/site-packages/letsencrypt_plesk/challenge.py", line 47, in _put_validation_file
    hosting_props = api_result['data']['hosting']['vrt_hst']['property']
KeyError: 'vrt_hst'

2015-12-31 14:48:30,498:DEBUG:letsencrypt.error_handler:Calling registered functions
2015-12-31 14:48:30,498:INFO:letsencrypt.auth_handler:Cleaning up challenges
2015-12-31 14:48:30,499:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/psa/var/modules/letsencrypt//venv/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/psa/var/modules/letsencrypt/venv.qKGL3/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1396, in main
    return args.func(args, config, plugins)
  File "/usr/local/psa/var/modules/letsencrypt/venv.qKGL3/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 557, in run
    lineage = _auth_from_domains(le_client, config, domains)
  File "/usr/local/psa/var/modules/letsencrypt/venv.qKGL3/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 402, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/usr/local/psa/var/modules/letsencrypt/venv.qKGL3/local/lib/python2.7/site-packages/letsencrypt/client.py", line 283, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/local/psa/var/modules/letsencrypt/venv.qKGL3/local/lib/python2.7/site-packages/letsencrypt/client.py", line 266, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/usr/local/psa/var/modules/letsencrypt/venv.qKGL3/local/lib/python2.7/site-packages/letsencrypt/client.py", line 224, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/usr/local/psa/var/modules/letsencrypt/venv.qKGL3/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 80, in get_authorizations
    cont_resp, dv_resp = self._solve_challenges()
  File "/usr/local/psa/var/modules/letsencrypt/venv.qKGL3/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 115, in _solve_challenges
    dv_resp = self.dv_auth.perform(self.dv_c)
  File "/usr/local/psa/var/modules/letsencrypt/venv.qKGL3/local/lib/python2.7/site-packages/letsencrypt_plesk/configurator.py", line 75, in perform
    responses.append(self.plesk_challenges[domain].perform(x))
  File "/usr/local/psa/var/modules/letsencrypt/venv.qKGL3/local/lib/python2.7/site-packages/letsencrypt_plesk/challenge.py", line 31, in perform
    content=validation.encode())
  File "/usr/local/psa/var/modules/letsencrypt/venv.qKGL3/local/lib/python2.7/site-packages/letsencrypt_plesk/challenge.py", line 47, in _put_validation_file
    hosting_props = api_result['data']['hosting']['vrt_hst']['property']
KeyError: 'vrt_hst' ```

**Comment by xgin** [comment]
@Huskynarr The site you created seems to have no physical hosting.
We should certainly improve error reporting in this case.

**Comment by Huskynarr** [comment]
What do you mean exactly with Physical Hosting?
I have it as Site and hosting a page there.

**Comment by xgin** [comment]
In Plesk interface click `Hosting Settings` under the domain, here you will see a `Hosting type` field - it should be `Website` in order to use Let's Encypt.

**Comment by Huskynarr** [comment]
That was the Problem. :) 
Now i have a another Problem, but this i a Error from Letsencrypt. :D

**Comment by coodec** [comment]
Hi, I would like to use let's encrypt with Odoo, which uses the port 8069, there is any way to get it to work...
