### ISSUE TITLE
Error creating certificate for "no hosting"-domain

### ISSUE THREAD

**Issue by Hativ3** [plesk/letsencrypt-plesk#69]
I've created the plesk control panel domain as "no hosting"-domain to secure it with let's encrypt certificate, but I get the following error:

```
2016-01-31 10:01:39,902:DEBUG:letsencrypt.cli:Root logging level set at 30
2016-01-31 10:01:39,902:INFO:letsencrypt.cli:Saving debug log to /opt/psa/var/modules/letsencrypt/logs/letsencrypt.log
2016-01-31 10:01:39,903:DEBUG:letsencrypt.cli:letsencrypt version: 0.3.0
2016-01-31 10:01:39,903:DEBUG:letsencrypt.cli:Arguments: ['--renew-by-default', '--no-redirect', '--agree-tos', '--text', '--config-dir', '/opt/psa/var/modules/letsencrypt//etc', '--work-dir', '/opt/psa/var/modules/letsencrypt//lib', '--logs-dir', '/opt/psa/var/modules/letsencrypt//logs', '--authenticator', 'letsencrypt-plesk:plesk', '--installer', 'letsencrypt-plesk:plesk', '--email', 'admin@example.com', '-d', 'plesk.example.com', '--letsencrypt-plesk:plesk-secure-panel']
2016-01-31 10:01:39,903:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#letsencrypt-plesk:plesk,PluginEntryPoint#standalone)
2016-01-31 10:01:39,903:WARNING:letsencrypt.cli:Root (sudo) is required to run most of letsencrypt functionality.
2016-01-31 10:01:39,903:DEBUG:letsencrypt.cli:Requested authenticator letsencrypt-plesk:plesk and installer letsencrypt-plesk:plesk
2016-01-31 10:01:39,906:DEBUG:letsencrypt.display.ops:Single candidate plugin: * letsencrypt-plesk:plesk
Description: Plesk
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: plesk = letsencrypt_plesk.configurator:PleskConfigurator
Initialized: <letsencrypt_plesk.configurator.PleskConfigurator object at 0x32ec2d0>
Prep: True
2016-01-31 10:01:39,906:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt_plesk.configurator.PleskConfigurator object at 0x32ec2d0> and installer <letsencrypt_plesk.configurator.PleskConfigurator object at 0x32ec2d0>
2016-01-31 10:01:39,915:DEBUG:letsencrypt.cli:Picked account: <Account(964df479b36b6eb42129c8e876450c94)>
2016-01-31 10:01:39,916:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-01-31 10:01:39,919:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-01-31 10:01:40,076:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
2016-01-31 10:01:40,079:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Sun, 31 Jan 2016 10:01:40 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Sun, 31 Jan 2016 10:01:40 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'YWgT-2oEt3CNOAtOD2t9_RAWF1fY80hdOnUT3_ytpO8'}. Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2016-01-31 10:01:40,089:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Sun, 31 Jan 2016 10:01:40 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Sun, 31 Jan 2016 10:01:40 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'YWgT-2oEt3CNOAtOD2t9_RAWF1fY80hdOnUT3_ytpO8'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2016-01-31 10:01:40,236:INFO:letsencrypt.crypto_util:Generating key (2048 bits): /opt/psa/var/modules/letsencrypt/etc/keys/0006_key-letsencrypt.pem
2016-01-31 10:01:40,238:INFO:letsencrypt.crypto_util:Creating CSR: /opt/psa/var/modules/letsencrypt/etc/csr/0006_csr-letsencrypt.pem
2016-01-31 10:01:40,238:DEBUG:letsencrypt.client:CSR: CSR(file='/opt/psa/var/modules/letsencrypt/etc/csr/0006_csr-letsencrypt.pem', data='0\x82\x02\x8f0\x82\x01w\x02\x000\x1c1\x1a0\x18\x06\x03U\x04\x03\x0c\x11plesk.example.com0\x82\x01"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x0f\x000\x82\x01\n\x02\x82\x01\x01\x00\x9d\xdew\xb1\x90bF\xadJ\x85h\xdd\x9aFm\xaa\nL\x89w\xb2\x10\xc4\x88Po\xa0\x12\xf1a\x02\xd0\x81)\xd7L\xdc\xbd\x82\x9f\xb3/\x96\xad\xaa\xd2;\xa9\xe0$-\xb7\xf0}\xa3dD$R\xf3O\x15X\xad\x99VHp \x17f+F\'\x0c\x88\xbb\xd4\xbb\xb1\x7f3\xdb\xf3h\x1d\x9a_@i~\x91\']\xa58\xd5\'m\xf5`"_\xdd\xba\x10\xd87\xb8\xe0iK,\x19G\xe9\xa2\x17t$\x96j\x0f\xf2{\xc1\xeb\xecz]:\xd6\xd2B\xd1C\xa3\xc1\x93\x11\xb3K6\xaf\xe2Lv\x98\x17\xc96Ym\xc0f\xa5\xd0\xeaJ\xa0\x81\x909\xce\x1f\xffy\x8d\x88W+(V}\xf0\xe8\x06]J\xe6\xd1:\xe9\xae42_\x1b\xe3\xd1\xcc.&\x89(\xeb[\xa4\x0c\xed\x8c|\x00[\xedC\xa3SOk`\x1b;\x83\xb4\xb6W\xff\xfb\x08\xfb\xd0\xcd\x08\xae\x08\xb4\'K2\xea[\xdd^\xeaw\x0b\xdfr\xcad U\xa5\x17k\xdd\xbf\xe1\xc3s2\x7f\xd5p\xd3\x02\x03\x01\x00\x01\xa0/0-\x06\t*\x86H\x86\xf7\r\x01\t\x0e1 0\x1e0\x1c\x06\x03U\x1d\x11\x04\x150\x13\x82\x11plesk.example.com0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x01\x01\x00\x10\x9d\x0c\r\xae\xcf\xa3|\x10\x1f\x11\x01n#J\xdc\xb4\xf2\x89F\xf4\xc0p\xdc\x01,\xba\x07\xf4X\x10\xa71B\xc1uf8\x15Y\xdb\xa3\xe8,\xfaB\xb6g\xf4K\x100"A\x0b\xac\x8b$`\xa4\xb9Y\xda!Lo\xf7\x02\x0b\xa1\xe3\xf1\xe3n\xe5\xb4K\xa0\x1b\xaboCp{/\x11\xb4Xe\xc2\xcf\xc16\x8f\xe4\x0f\x19\xb4\xa1\xfe\x98rp\x925<eo\x93\x80\xc2Y\xa2HfU\x05\n\x9a\xbd\x82\xec\xe9\x04\xd55\x0b\xeb!Y(\xb3\xfe\x8dV\x08>\xa5Z\x13F\xc5\xd2\xa3\xc6\xdc\x92\x045\xd6\xbe\xd2\xb8\xedd\xe0\xa9\xa8\xce\xa1\xc7\xcao:\xae\xf1\xfb\xca\xc2\x1a&\xe7\xdf\xe7\x1d\x90S\xe2\xc6Z\xb8\x13\x8e\xd3\x9d\xe6`.I!\xcb\x8a\xc5\xf4\xbdU\x81\xe4]\x9a,e\xc6\xa6\xc70\xce\x18\x1f\x9d\x8d\x04\xf7\xean3\x84/)=~&\xb7\xe4O\x02\xfc\xcdFx\x84\x16\xf9\xba\xd7\xaf\xa7E{ff\x81\xf1^hgn\xf0\xb5\xc0\x05\xf1Zo/\xbe', form='der'), domains: ['plesk.example.com']
2016-01-31 10:01:40,238:DEBUG:root:Requesting fresh nonce
2016-01-31 10:01:40,238:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {}
2016-01-31 10:01:40,239:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-01-31 10:01:40,667:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-authz HTTP/1.1" 405 0
2016-01-31 10:01:40,669:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '78', 'Pragma': 'no-cache', 'Expires': 'Sun, 31 Jan 2016 10:01:41 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Sun, 31 Jan 2016 10:01:41 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'mDjItT7NtblI3tV6x5oSYjBokgY19kOmourIaxi2CRI'}. Content: ''
2016-01-31 10:01:40,670:DEBUG:acme.client:Storing nonce: '\x988\xc8\xb5>\xcd\xb5\xb9H\xde\xd5z\xc7\x9a\x12b0h\x92\x065\xf6C\xa6\xa2\xea\xc8k\x18\xb6\t\x12'
2016-01-31 10:01:40,671:DEBUG:acme.jose.json_util:Omitted empty fields: combinations=None, challenges=None, expires=None, status=None
2016-01-31 10:01:40,671:DEBUG:acme.client:Serialized JSON: {"identifier": {"type": "dns", "value": "plesk.example.com"}, "resource": "new-authz"}
2016-01-31 10:01:40,673:DEBUG:acme.jose.json_util:Omitted empty fields: kid=None, x5c=(), crit=(), typ=None, jwk=None, alg=None, jku=None, cty=None, x5tS256=None, x5u=None, x5t=None
2016-01-31 10:01:40,675:DEBUG:acme.jose.json_util:Omitted empty fields: kid=None, x5c=(), crit=(), typ=None, jku=None, cty=None, x5tS256=None, x5u=None, x5t=None, nonce=None
2016-01-31 10:01:40,675:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "qbfywafsVv_vapIkQ2fE50vg-Mo86miGgkvnosqm5pg04zddL5U1PHMS6NX6wclTtClsUaJT4g498jArKJgX46gU9fHp-W5-xc_XmCPrbSj9NOM25E__laiXq2rFBjAIA9tMgR19CGdg65jTBVk557_EWUyy-7NW0A9HbwXV9QQ411HLcT18R0GcI7Dx9AClivWdTrojMNlT2WNW7mbsNH3mB4zEbNZssAfRvcc2bdkyny3x3WOPtr1McrQsw1uU0LnmWnjinD8SXCPsRAjdojpY38C2koTRiKl87flMbbLFg0l_Sh1qDR5wbc0VGKn46gY-f_6EqSSlHIjSSAk1zw"}}, "protected": "eyJub25jZSI6ICJtRGpJdFQ3TnRibEkzdFY2eDVvU1lqQm9rZ1kxOWtPbW91cklheGkyQ1JJIn0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJsaXZlMi52aXNpb3Byby5ldSJ9LCAicmVzb3VyY2UiOiAibmV3LWF1dGh6In0", "signature": "mKllPkI5DpBBdJE13QTvXX4OspojO7CQiBo2rq15q_U3lDgb0QRPzzMDUwdusn590ajO1ygRhmGvFETDNC9f1yg6tQxV-VkYY9mctZ7FhFmdEdsWa8T8GTaQs2kRsr8pJs9VHru3lr-fZozcZ6IpbFnTRsaedXqqZQp99RmeJOQ1zR7zxs0zTirzqYmJ0ios6NOxnPxQLcPn_w3-DuCruE2tcGAxGbzmOK_748alsKA1HKpz9LEX0jyHNGl3-O9eVnZuGJSsjPwSREs8yzf-vTNGWyt_Zi8yoo9NPu2zWQSl3DsHBNYvgCEhZ22DE1Q03olwjLBwDrg_R6g_BRTALQ"}'}
2016-01-31 10:01:40,676:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-01-31 10:01:40,884:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 201 780
2016-01-31 10:01:40,887:DEBUG:root:Received <Response [201]>. Headers: {'Content-Length': '780', 'Expires': 'Sun, 31 Jan 2016 10:01:41 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/authz/9PnawgKmuCicBNbnyK_4i_ZSTqvAPvtghVPKDETrr2E', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Sun, 31 Jan 2016 10:01:41 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'RGrhv2E_fTbPLxvTG8GyhCPRdFlkLOLHmvalm79TBfk'}. Content: '{"identifier":{"type":"dns","value":"plesk.example.com"},"status":"pending","expires":"2016-02-07T10:01:41.677427656Z","challenges":[{"type":"tls-sni-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/9PnawgKmuCicBNbnyK_4i_ZSTqvAPvtghVPKDETrr2E/12779623","token":"Zt8dS-SF2Qd9NiG22U1Q2AmSLqPQ7DtxPE-vVXQxCko"},{"type":"dns-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/9PnawgKmuCicBNbnyK_4i_ZSTqvAPvtghVPKDETrr2E/12779624","token":"hlzz5WAYxZ8VJKfH-e28LQiHPRxyzWt6ABjOe_EkCg0"},{"type":"http-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/9PnawgKmuCicBNbnyK_4i_ZSTqvAPvtghVPKDETrr2E/12779625","token":"hLakZvtoSdzO-otxpHZJOlvqxAzsNMcxFInz34aIRyE"}],"combinations":[[0],[2],[1]]}'
2016-01-31 10:01:40,888:DEBUG:acme.client:Storing nonce: 'Dj\xe1\xbfa?}6\xcf/\x1b\xd3\x1b\xc1\xb2\x84#\xd1tYd,\xe2\xc7\x9a\xf6\xa5\x9b\xbfS\x05\xf9'
2016-01-31 10:01:40,888:DEBUG:acme.client:Received response <Response [201]> (headers: {'Content-Length': '780', 'Expires': 'Sun, 31 Jan 2016 10:01:41 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/authz/9PnawgKmuCicBNbnyK_4i_ZSTqvAPvtghVPKDETrr2E', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Sun, 31 Jan 2016 10:01:41 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'RGrhv2E_fTbPLxvTG8GyhCPRdFlkLOLHmvalm79TBfk'}): '{"identifier":{"type":"dns","value":"plesk.example.com"},"status":"pending","expires":"2016-02-07T10:01:41.677427656Z","challenges":[{"type":"tls-sni-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/9PnawgKmuCicBNbnyK_4i_ZSTqvAPvtghVPKDETrr2E/12779623","token":"Zt8dS-SF2Qd9NiG22U1Q2AmSLqPQ7DtxPE-vVXQxCko"},{"type":"dns-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/9PnawgKmuCicBNbnyK_4i_ZSTqvAPvtghVPKDETrr2E/12779624","token":"hlzz5WAYxZ8VJKfH-e28LQiHPRxyzWt6ABjOe_EkCg0"},{"type":"http-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/9PnawgKmuCicBNbnyK_4i_ZSTqvAPvtghVPKDETrr2E/12779625","token":"hLakZvtoSdzO-otxpHZJOlvqxAzsNMcxFInz34aIRyE"}],"combinations":[[0],[2],[1]]}'
2016-01-31 10:01:40,889:DEBUG:acme.challenges:dns-01 was not recognized, full message: {u'status': u'pending', u'token': u'hlzz5WAYxZ8VJKfH-e28LQiHPRxyzWt6ABjOe_EkCg0', u'type': u'dns-01', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/9PnawgKmuCicBNbnyK_4i_ZSTqvAPvtghVPKDETrr2E/12779624'}
2016-01-31 10:01:40,890:INFO:letsencrypt.auth_handler:Performing the following challenges:
2016-01-31 10:01:40,890:INFO:letsencrypt.auth_handler:http-01 challenge for plesk.example.com
2016-01-31 10:01:40,895:DEBUG:letsencrypt_plesk.api_client:Plesk API-RPC request: <?xml version="1.0" ?><packet><site><get><filter><name>plesk.example.com</name></filter><dataset><hosting/></dataset></get></site></packet>
2016-01-31 10:01:40,896:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): 127.0.0.1
2016-01-31 10:01:41,099:DEBUG:requests.packages.urllib3.connectionpool:"POST /enterprise/control/agent.php HTTP/1.1" 200 None
2016-01-31 10:01:41,101:DEBUG:letsencrypt_plesk.api_client:Plesk API-RPC response: <?xml version="1.0" encoding="UTF-8"?>
<packet version="1.6.7.0">
  <site>
    <get>
      <result>
        <status>ok</status>
        <filter-id>plesk.example.com</filter-id>
        <id>325</id>
        <data>
          <gen_info>
            <cr_date>2016-01-31</cr_date>
            <name>plesk.example.com</name>
            <ascii-name>plesk.example.com</ascii-name>
            <status>0</status>
            <real_size>0</real_size>
            <dns_ip_address>10.10.10.10</dns_ip_address>
            <htype>none</htype>
            <guid>af51d336-4670-4372-bdfa-3797c59811a9</guid>
            <webspace-guid>84995608-de3c-5e83-a671-cf592802aa0c</webspace-guid>
            <sb-site-uuid/>
            <webspace-id>226</webspace-id>
            <description/>
          </gen_info>
          <hosting>
            <none/>
          </hosting>
        </data>
      </result>
    </get>
  </site>
</packet>

2016-01-31 10:01:41,104:DEBUG:letsencrypt.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/psa/var/modules/letsencrypt/venv.BnVBB/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 115, in _solve_challenges
    dv_resp = self.dv_auth.perform(self.dv_c)
  File "/usr/local/psa/var/modules/letsencrypt/venv.BnVBB/local/lib/python2.7/site-packages/letsencrypt_plesk/configurator.py", line 75, in perform
    responses.append(self.plesk_challenges[domain].perform(x))
  File "/usr/local/psa/var/modules/letsencrypt/venv.BnVBB/local/lib/python2.7/site-packages/letsencrypt_plesk/challenge.py", line 31, in perform
    content=validation.encode())
  File "/usr/local/psa/var/modules/letsencrypt/venv.BnVBB/local/lib/python2.7/site-packages/letsencrypt_plesk/challenge.py", line 47, in _put_validation_file
    hosting_props = api_result['data']['hosting']['vrt_hst']['property']
KeyError: 'vrt_hst'

2016-01-31 10:01:41,104:DEBUG:letsencrypt.error_handler:Calling registered functions
2016-01-31 10:01:41,104:INFO:letsencrypt.auth_handler:Cleaning up challenges
2016-01-31 10:01:41,105:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/psa/var/modules/letsencrypt//venv/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/psa/var/modules/letsencrypt/venv.BnVBB/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1454, in main
    return args.func(args, config, plugins)
  File "/usr/local/psa/var/modules/letsencrypt/venv.BnVBB/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 598, in run
    lineage, action = _auth_from_domains(le_client, config, domains)
  File "/usr/local/psa/var/modules/letsencrypt/venv.BnVBB/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 418, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/usr/local/psa/var/modules/letsencrypt/venv.BnVBB/local/lib/python2.7/site-packages/letsencrypt/client.py", line 283, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/local/psa/var/modules/letsencrypt/venv.BnVBB/local/lib/python2.7/site-packages/letsencrypt/client.py", line 266, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/usr/local/psa/var/modules/letsencrypt/venv.BnVBB/local/lib/python2.7/site-packages/letsencrypt/client.py", line 224, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/usr/local/psa/var/modules/letsencrypt/venv.BnVBB/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 80, in get_authorizations
    cont_resp, dv_resp = self._solve_challenges()
  File "/usr/local/psa/var/modules/letsencrypt/venv.BnVBB/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 115, in _solve_challenges
    dv_resp = self.dv_auth.perform(self.dv_c)
  File "/usr/local/psa/var/modules/letsencrypt/venv.BnVBB/local/lib/python2.7/site-packages/letsencrypt_plesk/configurator.py", line 75, in perform
    responses.append(self.plesk_challenges[domain].perform(x))
  File "/usr/local/psa/var/modules/letsencrypt/venv.BnVBB/local/lib/python2.7/site-packages/letsencrypt_plesk/challenge.py", line 31, in perform
    content=validation.encode())
  File "/usr/local/psa/var/modules/letsencrypt/venv.BnVBB/local/lib/python2.7/site-packages/letsencrypt_plesk/challenge.py", line 47, in _put_validation_file
    hosting_props = api_result['data']['hosting']['vrt_hst']['property']
KeyError: 'vrt_hst'
```

It doesn't matter if I tick "Use this certificate to secure connections to Plesk." or not.

Real domain masked as "plesk.example.com", IP as "10.10.10.10" and email address as "admin@plesk.example.com".

**Comment by stayallive** [comment]
Since there is no hosting there is no webroot for Plesk to create the challenge file for Let's Encrypt.

What are you trying to secure on a domain that has nothing hosted?

**Comment by xgin** [comment]
If you want to use a domain without web hosting, check out the script for secure Plesk: https://gist.github.com/xgin/fbfa4577ad46955f472c
A certificate for `HOSTNAME=$(hostname)` is created, but you can replace the line of code with your domain name, if it differs from the hostname.
