### ISSUE TITLE
Renew certificates generates errors

### ISSUE THREAD

**Issue by RobertBoes** [plesk/letsencrypt-plesk#77]
First of, I'm sorry if this is the wrong place to ask this, but I've searched the KB and couldn't find a answer to my problem.

I have a few domains setup with Let's Encrypt, and I noticed the certificates are not updating each month so I ran the task manually which gave me the following error:
```
ERROR: pm_Exception: Unable to load object of type Domain with id=1: Domain does not exist. (Domain.php:28)<br />
<br><a href='http://kb.odin.com/plesk-error/search?metaId=25b205c19751edb19724260331564cfa&messageId=fe4d681c26d6b01bf87bad966bc68547&file=Domain.php&line=28&type=pm_Exception&version=12.5.30&message=Unable+to+load+object+of+type+Domain+with+id%3D%3A+Domain+does+not+exist.' target='_blank'>Search for related Knowledge Base articles</a>

[2016-02-18 20:36:53] ERR [extension/letsencrypt] Cannot renew certificate on domain with error: Failed letsencrypt execution: Traceback (most recent call last):
File "/usr/local/psa/var/modules/letsencrypt/venv/bin/letsencrypt", line 11, in <module>
sys.exit(main())
File "/usr/local/psa/var/modules/letsencrypt/venv.0bYBy/lib/python2.7/site-packages/letsencrypt/cli.py", line 1936, in main
args = prepare_and_parse_args(plugins, cli_args)
File "/usr/local/psa/var/modules/letsencrypt/venv.0bYBy/lib/python2.7/site-packages/letsencrypt/cli.py", line 1628, in prepare_and_parse_args
return helpful.parse_args()
File "/usr/local/psa/var/modules/letsencrypt/venv.0bYBy/lib/python2.7/site-packages/letsencrypt/cli.py", line 1202, in parse_args
parsed_args = self.parser.parse_args(self.args)
File "/usr/local/psa/var/modules/letsencrypt/venv.0bYBy/lib/python2.7/site-packages/configargparse.py", line 216, in parse_args
env_vars = env_vars)
File "/usr/local/psa/var/modules/letsencrypt/venv.0bYBy/lib/python2.7/site-packages/configargparse.py", line 349, in parse_known_args
self, args=args, namespace=namespace)
File "/usr/lib64/python2.7/argparse.py", line 1720, in parse_known_args
namespace, args = self._parse_known_args(args, namespace)
File "/usr/lib64/python2.7/argparse.py", line 1926, in _parse_known_args
start_index = consume_optional(start_index)
File "/usr/lib64/python2.7/argparse.py", line 1866, in consume_optional
take_action(action, args, option_string)
File "/usr/lib64/python2.7/argparse.py", line 1794, in take_action
action(self, namespace, argument_values, option_string)
File "/usr/local/psa/var/modules/letsencrypt/venv.0bYBy/lib/python2.7/site-packages/letsencrypt/cli.py", line 1827, in __call__
_process_domain(args, domain_arg)
File "/usr/local/psa/var/modules/letsencrypt/venv.0bYBy/lib/python2.7/site-packages/letsencrypt/cli.py", line 1808, in _process_domain
domain = le_util.enforce_domain_sanity(domain)
File "/usr/local/psa/var/modules/letsencrypt/venv.0bYBy/lib/python2.7/site-packages/letsencrypt/le_util.py", line 326, in enforce_domain_sanity
raise errors.ConfigurationError("Requested domain {0} is not a FQDN".format(domain))
ConfigurationError: Requested domain is not a FQDN

[2016-02-18 20:36:53] ERR [panel] Unable to load object of type Domain with id=1: Domain does not exist.:
0: /usr/local/psa/admin/plib/pm/Domain.php:28
pm_Domain->__construct(integer '1')
1: /usr/local/psa/admin/plib/modules/letsencrypt/library/Task/RenewCertificates.php:12
Modules_Letsencrypt_Task_RenewCertificates::run()
2: /usr/local/psa/admin/plib/modules/letsencrypt/scripts/renew-certificates.php:14
```

What could cause this issue? I have the most recent version of letsencrypt-plesk (1.3-1).

**Comment by xgin** [comment]
Could you show the output of the following commands:
```
curl -s -k https://localhost:8443/enterprise/control/agent.php -H "HTTP_AUTH_LOGIN: admin" -H "HTTP_AUTH_PASSWD: `plesk bin admin --show-password`" -H "HTTP_PRETTY_PRINT: true" -H "Content-Type: text/xml" -d "<packet><site><get><filter><id>1</id></filter><dataset><gen_info/></dataset></get></site></packet>"

curl -s -k https://localhost:8443/enterprise/control/agent.php -H "HTTP_AUTH_LOGIN: admin" -H "HTTP_AUTH_PASSWD: `plesk bin admin --show-password`" -H "HTTP_PRETTY_PRINT: true" -H "Content-Type: text/xml" -d "<packet><webspace><get><filter></filter><dataset><gen_info/></dataset></get></webspace></packet>"

curl -s -k https://localhost:8443/enterprise/control/agent.php -H "HTTP_AUTH_LOGIN: admin" -H "HTTP_AUTH_PASSWD: `plesk bin admin --show-password`" -H "HTTP_PRETTY_PRINT: true" -H "Content-Type: text/xml" -d "<packet><site><get><filter></filter><dataset><gen_info/></dataset></get></site></packet>"
```

We should certainly make the renew task more robust.

**Comment by xgin** [comment]
I have just understood the reason of failure, we will release the fix in a new version asap.

**Comment by mrclschstr** [comment]
+1 same issue here!

**Comment by xgin** [comment]
Check out the newest extension version 1.4 - the issue should be fixed

**Comment by mrclschstr** [comment]
Works perfectly, thank you!
